backend:
  name: git-gateway
  branch: main # 또는 master
media_folder: "images"
public_folder: "/images"
collections:
  - name: "projects"
    label: "프로젝트"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "설명", name: "body", widget: "markdown"}
      - {label: "대표 이미지", name: "thumbnail", widget: "image"}
